### PR TITLE
resolving merge conflict

### PR DESCRIPTION
**Pull request by joewiz**
Hi Adam,

I was preparing to merge your PR updating the map syntax to the latest XQuery 3.1 spec, but encountered a merge conflict. I thought of asking you to resolve it but then wondered if I could resolve it and send you a PR with the change. If this works for you, please accept, and then I'll merge the updated original PR. Or if this is introduces too much cruft into the history, please resolve the merge using your own methods - and just close this PR. 

Cheers,
Joe

### CODE REVIEW

**Comment by joewiz** [comment]
Darn, I chose your master branch instead of your develop branch. Selecting your develop branch indicates that there will be merge conflicts. So I'm going to preemptively close this and ask that you resolve the conflict between your PR and the current develop branch of eXide. Thanks.

**Comment by adamretter** [comment]
@joewiz Okay no worries. Just for future reference you don't need to close a PR for me to modify it and fix such things, I can do that with the same PR that is open. Anyway I have rebased to resolve the merge conflict and will open a new PR for you now.

**Comment by adamretter** [comment]
@joewiz Ah okay I see this was a different PR that you created. The original (but now rebased PR without merge conflicts) is https://github.com/wolfgangmm/eXide/pull/95, enjoy :-)

**Comment by joewiz** [comment]
Thanks so much, Adam! Merged.

**Pull request closed without merging**
